---

- name: install numix theme - add numix ppa
  apt_repository:
    repo: 'ppa:numix/ppa'
    state: present
    update_cache: yes
  become: yes

- name: install numix theme - install circle icon theme
  apt:
    name: numix-icon-theme-circle
    update_cache: yes
  become: yes

- name: install numix theme - install gtk theme
  apt:
    name: numix-gtk-theme
    update_cache: yes
  become: yes

- name: install numix theme - set gtk theme to Numix
  command: 'xfconf-query -c xsettings -p /Net/ThemeName -s "Numix"'

- name: install numix theme - set icons to circle
  command: xfconf-query -c xsettings -p /Net/IconThemeName -s "Numix-Circle"

- name: Set window theme
  command: xfconf-query -c xfwm4 -p /general/theme -s Numix

- name: Set window title font
  command: 'xfconf-query -c xfwm4 -p /general/title_font -s "Fira Sans 11"'
