---

- name: install numix theme - add numix ppa
  apt_repository:
    repo: 'ppa:numix/ppa'
    state: present
    update_cache: yes
  sudo: yes

- name: install numix theme - install circle icon theme
  apt:
    name: numix-icon-theme-circle
    update_cache: yes
  sudo: yes

- name: install numix theme - install gtk theme
  apt:
    name: numix-gtk-theme
    update_cache: yes
  sudo: yes

- name: install numix theme - set gtk theme to Numix
  command: 'xfconf-query -c xsettings -p /Net/ThemeName -s "Numix"'

- name: install numix theme - set icons to circle
  command: xfconf-query -c xsettings -p /Net/IconThemeName -s "Numix-Circle"
