---

# - name: Disable xscreensaver
#   become: true
#   apt:
#     name: xscreensaver
#     state: absent

- name: Remove default panel
  command: "xfconf-query -c xfce4-panel -p /panels -t int -s 1 -a"

- name: Reload panels
  command: xfce4-panel -r

- name: Create autostart dir
  file:
    path: ~/.config/autostart
    state: directory

- name: Autostart plank
  copy:
    src: files/plank.desktop
    dest: ~/.config/autostart/plank.desktop
