- name: a playbook to setup my local machine with my basic customizations
  hosts: default
  connection: local
  vars_prompt:
    - name: atom_github_access_token
      prompt: Enter the github access_token for atom sync-settings

  pre_tasks:
    - name: upgrade packages
      apt:
        upgrade: full
        update_cache: yes
        cache_valid_time: 300
      become: yes

  roles:
    - role: local.terminal
      tags: terminal
    - role: local.development
      tags: development
    - role: local.atom
      tags: atom
    - role: local.fonts
      tags: fonts
    - role: local.theme
      tags: theme
    - role: local.chrome
      tags: chrome
    - role: avnes.ansible-role-plank
      tags: plank
      clock_dock_item_on: no
      clippy_dock_item_on: no
      desktop_dock_item_on: no
      trash_dock_item_on: no
      plank_dock_items:
        - { name: 'xfce4-terminal', path: '/usr/share/applications/xfce4-terminal.desktop' }
        - { name: 'atom', path: '/usr/share/applications/atom.desktop' }
        - { name: 'chrome-browser', path: '/usr/share/applications/google-chrome.desktop' }
    - role: local.desktop
      tags: desktop
