- name: a playbook to setup my local machine with my basic customizations
  hosts: default
  connection: local
  vars_prompt:
    - name: atom_github_access_token
      prompt: Enter the github access_token for atom sync-settings
    - name: ssh_key
      prompt: Enter the ssh private key to be used

  roles:
    - local.ssh
    - local.terminal
    - local.nodejs
    - local.desktop
    - local.atom
    - local.fonts
    - local.theme
    - local.chrome
    - role: avnes.ansible-role-plank
      clock_dock_item_on: no
      clippy_dock_item_on: no
      desktop_dock_item_on: no
      trash_dock_item_on: no
      plank_dock_items:
        - { name: 'xfce4-terminal', path: '/usr/share/applications/xfce4-terminal.desktop' }
        - { name: 'atom', path: '/usr/share/applications/atom.desktop' }
        - { name: 'chrome-browser', path: '/usr/share/applications/google-chrome.desktop' }
