---

- name: Add fira fonts
  become: true
  copy:
    src: files/fonts/
    dest: /usr/share/fonts/opentype/

- name: Set font
  command: xfconf-query -c xsettings -p /Gtk/FontName -s "Fira Sans Light 10"

- name: Enable anti-alias
  command: xfconf-query -c xsettings -p /Xft/Antialias -s 1

- name: Enable hinting
  shell: |
    xfconf-query - c xsettings -p /Xft/Hinting -s -1
    xfconf-query - c xsettings -p /Xft/HintStyle -s hintmedium
