---

- name: Create ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: Add ssh key
  copy:
    content: "{{ ssh_key }}"
    dest: ~/.ssh/id_rsa
    mode: 0600

- name: Add ssh public key file
  file:
    path: ~/.ssh/id_rsa.pub
    state: touch
    mode: 0644

- name: Generate ssh public key
  shell: ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
