---

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

- name: install nodejs
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts=boron
  args:
    executable: /bin/bash

- name: install global nodejs packages
  shell: source {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install -g {{ item.name }}
  args:
    executable: /bin/bash
  with_items:
    - name: "bunyan"
    - name: "@google-cloud/functions-emulator"
