---

- name: Install common tools
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - curl
    - nano
    - git
    - lsof
    - apache2-utils

- name: Create terminal directory
  file:
    path: ~/.config/xfce4/terminal
    state: directory

- name: Copy terminalrc settings file
  copy:
    src: files/terminalrc
    dest: ~/.config/xfce4/terminal/terminalrc

- name: Download base16 colors
  git:
    repo: https://github.com/chriskempson/base16-shell
    dest: ~/.config/base16-shell

- name: Copy dotfiles
  copy:
    src: files/dotfiles/
    dest: "{{ ansible_env.HOME}}"

- name: Force color prompt in terminal
  lineinfile:
    dest: ~/.bashrc
    regexp: "force_color_prompt="
    line: "force_color_prompt=yes"

- name: Source bash customizations
  blockinfile:
    dest: ~/.bashrc
    block: |
      source ~/.bash_customizations
